services:
  web:
    container_name: portfolio-web
    build: .
    env_file:
      - .env
    ports:
      - "3000:3000"
    expose:
      - 3000
    depends_on:
      - redis
    volumes:
      - ./uploads:/srv/app/uploads
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
